[package]
name = "osu-skin-flipper"
version = "1.0.0"
edition = "2021"

[dependencies]
image = "0.24"
eframe = "0.21"
rfd = "0.11"
zip = "0.6"
walkdir = "2.3"
sysinfo = "0.28"
opener = "0.6"
include_dir = "0.7.3"
rust-ini = "0.18"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"